server:
  port: 8080
  servlet:
    context-path: /club

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/club?useSSL=false&serverTimezone=UTC&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*-mapper.xml
  type-aliases-package: com.spdb.club.entity
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true


